include:
   - board: nice_nano@2.0.0//zmk
     shield: splitkb_aurora_sweep_left
   - board: nice_nano@2.0.0//zmk
     shield: splitkb_aurora_sweep_right
   - board: nice_nano@2.0.0//zmk
     shield: settings_reset
