manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cdc-mkb
      url-base: https://github.com/cdc-mkb
    - name: jgreal
      url-base: https://github.com/jgreel/zmk
  projects:
    - name: zmk
      remote: jgreal
      revision: devel-mouse-pim447
      import: app/west.yml
  self:
    path: config
