manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: wieke
      url-base: https://github.com/wieke
  projects:
    - name: zmk
      remote: wieke
      revision: main
      import: app/west.yml
  self:
    path: config
